name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        ruby: [jruby-9.4.9.0, 3.3]
        java: [8]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          ./mvnw -ntp -B initialize
          bundle install --jobs=3 --retry=3

      - name: Run tests
        run: ./mvnw -ntp -B test
